name: Deb in vm
run-name: ${{ github.actor }} is doing stuff with VM
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    timeout-minutes: 2
    runs-on: self-hosted
    steps:
      - name: Build project
        run: |
          make build
      - run: echo "build complete"
  deb-package-stuff:
    timeout-minutes: 2
    runs-on: self-hosted
    steps:
      - run: echo "Building deb package"
      - name: build deb package
        run: |
          make build-deb
      - name: Archive deb package
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: |
            counter-v2.0.0.deb
      - run: echo "Archived deb package"
  scp-to-vm:
    timeout-minutes: 2
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "counter-v2.0.0.deb"
          target: "./"
  ssh-to-vm:
    timeout-minutes: 2
    runs-on: self-hosted
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo Hello from Github
            sudo dpkg -i counter-v2.0.0.deb
