name: SSH
run-name: ${{ github.actor }} is trying to make this work 🚀
on: [push]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 'instance-1'
        username: 'nisameshal'
        key: ${{ secrets.SSH_KEY }}
        script: whoami
